version: '3.4'

networks:
    default:
        name: games-scores
        driver: bridge

services:
  server:
    container_name: "game-scores"
    environment:
      PORT: "3030"
    ports:
      - "3030:3030"
    build:
      context: .
      dockerfile: Dockerfile