version: '3.4'

volumes:
  games-server-db:
    name: games-server-db

networks:
    default:
        driver: bridge

services:
  server:
    container_name: "game-scores"
    environment:
      PORT: "3030"
      CORS_ORIGIN: https://lambertjamesd.github.io
    ports:
      - "3030:3030"
    volumes:
      - "games-server-db:/usr/src/app/db"
    build:
      context: .
      dockerfile: Dockerfile