version: '3.4'

volumes:
  games-server-db:
    name: games-server-db

networks:
    default:
        name: games-scores
        driver: bridge

services:
  server:
    container_name: "game-scores"
    environment:
      PORT: "3030"
    ports:
      - "3030:3030"
      - "3031:3031"
    volumes:
      - "games-server-db:/usr/src/app/db"
      - "./cert:/usr/src/app/cert"
    build:
      context: .
      dockerfile: Dockerfile